spring.application.name=TouristReviewBackend

server.port=8081

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/tourist_review_tracker
spring.datasource.username=root
spring.datasource.password=@Siva2005

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt-secret=ThisIsMyVerySecureAndLongJwtSecretUsedOnlyForSigningTokensInSpringBootAndForItsSecurity!
app.jwt-expiration-milliseconds=3600000
